; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor
monitor_speed = 115200

; Upload + monitor port (replace COM3 with whatever Device Manager shows)
upload_port = COM4
monitor_port = COM4
upload_speed = 921600


; Library dependencies — list any libraries you'd install via Library Manager in Arduino IDE
lib_deps =
    adafruit/Adafruit MPU6050@^2.2.6
    adafruit/Adafruit Unified Sensor@^1.1.14

; Build flags — things you'd otherwise pass to gcc
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_LOOP_STACK_SIZE=16384

; Filesystem to use for SPIFFS / LittleFS
board_build.filesystem = littlefs
